### PR TITLE
BUG: Pin cuda-version in host environments

### LINKED ISSUE #41: CUDA 12.0 build on windows depends on `cuda-cudart >=12.1.105`
This [dependency](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Fwin-64%2Flibmagma_sparse-2.7.2-h82b23e0_2.conda#dependencies) then [forces](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Fwin-64%2Fcuda-cudart-12.1.105-h63175ca_0.conda#dependencies) `cuda-version >=12.1,<12.2.0a0`, which is not compatible with regular CUDA 12.0 compilation.

This then leads to failure in https://github.com/conda-forge/kaldi-feedstock/pull/47 (for linux it works because there are older libmagma_sparse builds that pull in cuda-cudart 12.0)

There was some discussion about this in #39, but nothing that seemed like explicitly choosing 12.1 components in the 12.0 build.

@conda-forge/magma CC @jakirkham

### PR DESCRIPTION
**Pull request by carterbox**
Ensure that host CUDA libraries match compiler version, so that run_exports match. Fixes #41 Closes #40

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carterbox** [comment]
@conda-forge-admin, please rerender

**Comment by carterbox** [comment]
@conda-forge-admin, please rerender

**Comment by carterbox** [comment]
Closes #40

**Comment by hmaarrfk** [comment]
did you repo patch as well? otherwise you will be in trouble ^_^

**Comment by carterbox** [comment]
> did you repo patch as well? otherwise you will be in trouble ^_^

No. Do you mean yank broken packages? ~~I don't think I repo patch helps because this PR changes the dependencies in the host section.~~

I see. These magma and libmagma-sparse are outputs, but they are built in the top-level, so I could patch the existing packages.

I still don't understand where the trouble happens. Won't the solver just use these new packages instead of the old ones?

**Comment by carterbox** [comment]
Depends on  https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/679

**Comment by h-vetinari** [comment]
> I still don't understand where the trouble happens. Won't the solver just use these new packages instead of the old ones?

I agree with @carterbox here. The repodata patch would not have been necessary, and is on many ways actively wrong/dangerous, because it overrides the run-export of the _actual_ cuda-packages in the host environment when those packages were built (i.e. we were building against 12.1 but now pretending that didn't happen; if any 12.1 symbol was used to create `libmagma_sparse`, the repodata patch will have broken that package).

This PR would have been wholly sufficient.

**Comment by hmaarrfk** [comment]
I agree that repo patching is not ideal.

I've had alot of trouble with the cuda 11.2 to 12.0 transition that happened over the last few months.

Often times it seems that the solver is choosing 11.8 even if 12.0 should be preferred (in my opinion as a user)
https://github.com/conda-forge/onnxruntime-feedstock/issues/110#issuecomment-1988464611

Often, when the version is the "same" it seems that the CUDA 11 packages are preferred by the solver for some reason.
Forcing `cuda-version=12` isn't a straight upgrade since some packages do not "transition" well https://github.com/conda-forge/conda-forge.github.io/issues/1894

My solution these days, is to effectively:

1. Uninstall cuda-version, and uninstall anything related to cuda from my environment.
2. Pray that it doesn't attempt to remove `__cuda` .
3. Install things in a single command specifying `cuda-version=12`

All to say, I think that cuda has added a new layer of complexity to solver and it hasn't really been the smoothest experience for me .

**Comment by jakirkham** [comment]
FWIW this PR LGTM

We could revert the repodata patch

As to pain points Mark, would love to learn more details. If you have more examples, could you please share a few? Happy to follow links

**Comment by carterbox** [comment]
> FWIW this PR LGTM

Same.

> We could revert the repodata patch

If anyone has problems with those patched packages, I'd prefer to yank them because this build should be sufficient to replace the previous build.

**Comment by jakirkham** [comment]
Good point. Yanking seems like a better approach

Thanks all! 🙏

**Comment by h-vetinari** [comment]
Marking stuff as broken (since "yanking" is PyPI terminology) should be done as a last resort. It breaks reproducibility of environments that may well have been working fine.

The longer a given build has been available, the higher the threshold for marking it broken. The correct approach here would be to undo the repo data patch (which is admittedly perhaps not urgently necessary).

**Comment by h-vetinari** [comment]
In any case, thanks for fixing #41 so quickly! 🙏

**Pull request merged**
